//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sprint3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifications_temp
    {
        public int Id { get; set; }
        public string content_text { get; set; }
        public string func { get; set; }
    }
}
